from app.domains.contents.schemas.blocks.block_response import BlockResponse
from app.domains.contents.schemas.chapters.chapter_create_response import ChapterCreateResponse
from app.domains.contents.schemas.chapters.chapter_response import ChapterResponse
from app.domains.contents.schemas.cp_response import CpResponse
from app.domains.contents.schemas.fase_response import FaseResponse
from app.domains.contents.schemas.module.module_create import ModuleCreate
from app.domains.contents.schemas.module.module_response import ModuleResponse
from app.domains.contents.schemas.blocks.regenerate_request import RegenerateRequest
from app.domains.contents.schemas.blocks.regenerate_response import RegenerateResponse
from app.domains.contents.schemas.module.module_progress_response import ModuleProgressResponse