from app.domains.contents.schemas.block_response import BlockResponse
from app.domains.contents.schemas.chapter_create_response import ChapterCreateResponse
from app.domains.contents.schemas.chapter_response import ChapterResponse
from app.domains.contents.schemas.cp_response import CpResponse
from app.domains.contents.schemas.fase_response import FaseResponse
from app.domains.contents.schemas.module_create import ModuleCreate
from app.domains.contents.schemas.module_response import ModuleResponse
from app.domains.contents.schemas.regenerate_request import RegenerateRequest
from app.domains.contents.schemas.regenerate_response import RegenerateResponse