"""seed refix

Revision ID: 00c61ef8dcd1
Revises: 8217779042ef
Create Date: 2026-09-14 11:58:44.338166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c61ef8dcd1'
down_revision: Union[str, Sequence[str], None] = '8217779042ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_requests', sa.Column('classroom_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_quiz_requests_classroom_id'), 'quiz_requests', ['classroom_id'], unique=False)
    op.create_foreign_key(None, 'quiz_requests', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_requests', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_requests_classroom_id'), table_name='quiz_requests')
    op.drop_column('quiz_requests', 'classroom_id')
    # ### end Alembic commands ###
