"""add classroom

Revision ID: 02d8d8443bfd
Revises: da716e905fa4
Create Date: 2026-09-08 01:57:32.743626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d8d8443bfd'
down_revision: Union[str, Sequence[str], None] = 'da716e905fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_column('teachers', 'school_id')
    # ### end Alembic commands ###
