"""change job

Revision ID: 04e39ed293dd
Revises: 12db9cb8137e
Create Date: 2026-09-11 21:38:38.816503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e39ed293dd'
down_revision: Union[str, Sequence[str], None] = '12db9cb8137e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_student_chapter_progress'), 'chapters_progress', type_='unique')
    op.create_index('ix_chapter_progress_user_chapter', 'chapters_progress', ['student_id', 'chapter_id'], unique=True)
    op.drop_index(op.f('ix_modules_published_classroom'), table_name='modules', postgresql_where="((status)::text = 'PUBLISH'::text)")
    op.create_index('idx_modules_title_trgm', 'modules', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_modules_classroom_status', 'modules', ['classroom_id', 'status'], unique=False)
    op.create_index('ix_modules_classroom_status_updated', 'modules', ['classroom_id', 'status', 'updated_at'], unique=False)
    op.drop_index(op.f('idx_student_classrooms_student_classroom'), table_name='student_classrooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_student_classrooms_student_classroom'), 'student_classrooms', ['student_id', 'classroom_id'], unique=False)
    op.drop_index('ix_modules_classroom_status_updated', table_name='modules')
    op.drop_index('ix_modules_classroom_status', table_name='modules')
    op.drop_index('idx_modules_title_trgm', table_name='modules', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_modules_published_classroom'), 'modules', ['classroom_id'], unique=False, postgresql_where="((status)::text = 'PUBLISH'::text)")
    op.drop_index('ix_chapter_progress_user_chapter', table_name='chapters_progress')
    op.create_unique_constraint(op.f('uq_student_chapter_progress'), 'chapters_progress', ['student_id', 'chapter_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
