"""fix foreing key

Revision ID: 12db9cb8137e
Revises: 9c8d3a181ca6
Create Date: 2026-09-11 00:26:23.038160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12db9cb8137e'
down_revision: Union[str, Sequence[str], None] = '9c8d3a181ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('modules_progress_student_id_fkey'), 'modules_progress', type_='foreignkey')
    op.create_foreign_key(None, 'modules_progress', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules_progress', type_='foreignkey')
    op.create_foreign_key(op.f('modules_progress_student_id_fkey'), 'modules_progress', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
