"""add soal jawaban

Revision ID: 4233808f1ab4
Revises: ae60159a3d24
Create Date: 2026-09-15 04:48:08.256820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4233808f1ab4'
down_revision: Union[str, Sequence[str], None] = 'ae60159a3d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soal_jawaban',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.CHAR(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('divergence_step', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('personalized_justification', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("selected_option IN ('A', 'B', 'C', 'D')", name='check_soal_jawaban_option'),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soal_id', 'student_id', name='uq_soal_jawaban_student')
    )
    op.create_index(op.f('ix_soal_jawaban_soal_id'), 'soal_jawaban', ['soal_id'], unique=False)
    op.create_index(op.f('ix_soal_jawaban_student_id'), 'soal_jawaban', ['student_id'], unique=False)
    op.create_table('soal_jawaban_langkah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jawaban_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jawaban_id'], ['soal_jawaban.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jawaban_id', 'urutan', name='uq_soal_jawaban_langkah_urutan')
    )
    op.create_index(op.f('ix_soal_jawaban_langkah_jawaban_id'), 'soal_jawaban_langkah', ['jawaban_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soal_jawaban_langkah_jawaban_id'), table_name='soal_jawaban_langkah')
    op.drop_table('soal_jawaban_langkah')
    op.drop_index(op.f('ix_soal_jawaban_student_id'), table_name='soal_jawaban')
    op.drop_index(op.f('ix_soal_jawaban_soal_id'), table_name='soal_jawaban')
    op.drop_table('soal_jawaban')
    # ### end Alembic commands ###
