"""soal jawaban fix

Revision ID: 42be485a902b
Revises: a3b3ed5a0e2e
Create Date: 2026-09-21 20:27:04.838729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42be485a902b'
down_revision: Union[str, Sequence[str], None] = 'a3b3ed5a0e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soal_jawaban', 'selected_option',
               existing_type=sa.CHAR(length=1),
               nullable=True)
    op.alter_column('soal_jawaban', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soal_jawaban', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('soal_jawaban', 'selected_option',
               existing_type=sa.CHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
