"""fix constrains

Revision ID: 4df55953f70f
Revises: 4ea1ee76b043
Create Date: 2026-09-16 20:51:23.574433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df55953f70f'
down_revision: Union[str, Sequence[str], None] = '4ea1ee76b043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_progress_student_id_fkey'), 'chapters_progress', type_='foreignkey')
    op.drop_constraint(op.f('chapters_progress_chapter_id_fkey'), 'chapters_progress', type_='foreignkey')
    op.create_foreign_key(None, 'chapters_progress', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chapters_progress', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters_progress', type_='foreignkey')
    op.drop_constraint(None, 'chapters_progress', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_progress_chapter_id_fkey'), 'chapters_progress', 'chapters', ['chapter_id'], ['id'])
    op.create_foreign_key(op.f('chapters_progress_student_id_fkey'), 'chapters_progress', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
