"""ai-annotation

Revision ID: 549b5af7f98e
Revises: 07f98ca77768
Create Date: 2026-09-10 00:09:04.427066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549b5af7f98e'
down_revision: Union[str, Sequence[str], None] = '07f98ca77768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('hots_count', sa.Integer(), nullable=False),
    sa.Column('lots_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='check_quiz_req_status'),
    sa.CheckConstraint('hots_count >= 0', name='check_quiz_req_hots'),
    sa.CheckConstraint('lots_count >= 0', name='check_quiz_req_lots'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_request_status', 'quiz_requests', ['status', 'id'], unique=False)
    op.create_index(op.f('ix_quiz_requests_module_id'), 'quiz_requests', ['module_id'], unique=False)
    op.create_table('quiz_request_chapters',
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_request_id', 'chapter_id')
    )
    op.create_table('soal_stimulus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('source_markup', sa.Text(), server_default='', nullable=False),
    sa.Column('readable_text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('source_reading_order_start', sa.Integer(), nullable=False),
    sa.Column('source_reading_order_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited')", name='check_stimulus_review'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soal_stimulus_chapter_id'), 'soal_stimulus', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_soal_stimulus_quiz_request_id'), 'soal_stimulus', ['quiz_request_id'], unique=False)
    op.create_table('soal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('stimulus_id', sa.Integer(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.CHAR(length=1), nullable=False),
    sa.Column('kesimpulan', sa.Text(), nullable=False),
    sa.Column('source_reading_order_start', sa.Integer(), nullable=False),
    sa.Column('source_reading_order_end', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('review_priority', sa.Text(), server_default='normal', nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("correct_option IN ('A', 'B', 'C', 'D')", name='check_soal_correct_opt'),
    sa.CheckConstraint("review_priority IN ('low', 'normal', 'high')", name='check_soal_priority'),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited')", name='check_soal_review'),
    sa.CheckConstraint('bloom_level BETWEEN 1 AND 6', name='check_soal_bloom'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stimulus_id'], ['soal_stimulus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soal_chapter_id'), 'soal', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_soal_quiz_request_id'), 'soal', ['quiz_request_id'], unique=False)
    op.create_index(op.f('ix_soal_stimulus_id'), 'soal', ['stimulus_id'], unique=False)
    op.create_table('soal_langkah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soal_id', 'urutan', name='uq_soal_langkah_urutan')
    )
    op.create_index(op.f('ix_soal_langkah_soal_id'), 'soal_langkah', ['soal_id'], unique=False)
    op.create_table('soal_opsi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.CHAR(length=1), nullable=False),
    sa.Column('opsi_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("label IN ('A', 'B', 'C', 'D')", name='check_opsi_label'),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soal_id', 'label', name='uq_soal_opsi_label')
    )
    op.create_index(op.f('ix_soal_opsi_soal_id'), 'soal_opsi', ['soal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soal_opsi_soal_id'), table_name='soal_opsi')
    op.drop_table('soal_opsi')
    op.drop_index(op.f('ix_soal_langkah_soal_id'), table_name='soal_langkah')
    op.drop_table('soal_langkah')
    op.drop_index(op.f('ix_soal_stimulus_id'), table_name='soal')
    op.drop_index(op.f('ix_soal_quiz_request_id'), table_name='soal')
    op.drop_index(op.f('ix_soal_chapter_id'), table_name='soal')
    op.drop_table('soal')
    op.drop_index(op.f('ix_soal_stimulus_quiz_request_id'), table_name='soal_stimulus')
    op.drop_index(op.f('ix_soal_stimulus_chapter_id'), table_name='soal_stimulus')
    op.drop_table('soal_stimulus')
    op.drop_table('quiz_request_chapters')
    op.drop_index(op.f('ix_quiz_requests_module_id'), table_name='quiz_requests')
    op.drop_index('ix_quiz_request_status', table_name='quiz_requests')
    op.drop_table('quiz_requests')
    # ### end Alembic commands ###
