"""change nullable

Revision ID: 708fd34e3341
Revises: 3c9e44de9cd4
Create Date: 2026-09-07 23:02:53.456660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708fd34e3341'
down_revision: Union[str, Sequence[str], None] = '3c9e44de9cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'nis',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'nisn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teachers_user_id_fkey'), 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('teachers_user_id_fkey'), 'teachers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.alter_column('students', 'grade',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('students', 'nisn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'nis',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
