"""seed refix

Revision ID: 749f9710254d
Revises: 00c61ef8dcd1
Create Date: 2026-09-15 00:37:18.915113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749f9710254d'
down_revision: Union[str, Sequence[str], None] = '00c61ef8dcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_requests', sa.Column('max_duration_minutes', sa.Integer(), nullable=False))
    op.add_column('quiz_requests', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('quiz_requests', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_requests', 'end_time')
    op.drop_column('quiz_requests', 'start_time')
    op.drop_column('quiz_requests', 'max_duration_minutes')
    # ### end Alembic commands ###
