"""seed refix

Revision ID: 8217779042ef
Revises: 6de434d35b64
Create Date: 2026-09-14 04:52:14.395241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8217779042ef'
down_revision: Union[str, Sequence[str], None] = '6de434d35b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_progress_student_request', 'quiz_progress', ['student_id', 'quiz_request_id'], unique=True)
    op.add_column('quiz_requests', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('quiz_requests', sa.Column('status_published', sa.Enum('DRAFT', 'PUBLISH', name='quizrequeststatus', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_requests', 'status_published')
    op.drop_column('quiz_requests', 'title')
    op.drop_index('ix_quiz_progress_student_request', table_name='quiz_progress')
    op.drop_table('quiz_progress')
    # ### end Alembic commands ###
