"""membuat tabel pertama

Revision ID: 9358acddd177
Revises: a1c9f0e3d21b
Create Date: 2026-09-14 15:18:15.174390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9358acddd177'
down_revision: Union[str, Sequence[str], None] = 'a1c9f0e3d21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_kb', 'anchor_embedding')
    op.drop_column('chapter_kb', 'anchor_text')
    op.add_column('chat_sessions', sa.Column('classroom_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_chat_sessions_student_chapter'), table_name='chat_sessions')
    op.create_index('ix_chat_sessions_student_classroom', 'chat_sessions', ['student_id', 'classroom_id'], unique=False)
    op.drop_constraint(op.f('chat_sessions_chapter_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_sessions', 'chapter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_chapter_id_fkey'), 'chat_sessions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_chat_sessions_student_classroom', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_student_chapter'), 'chat_sessions', ['student_id', 'chapter_id'], unique=False)
    op.drop_column('chat_sessions', 'classroom_id')
    op.add_column('chapter_kb', sa.Column('anchor_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chapter_kb', sa.Column('anchor_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
