"""membuat tabel pertama

Revision ID: 9735de6b6fe3
Revises: ea062bd0a1ec
Create Date: 2026-09-15 19:16:12.520893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9735de6b6fe3'
down_revision: Union[str, Sequence[str], None] = 'ea062bd0a1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_progress', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('quiz_progress', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_progress', sa.Column('review_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='quizreviewstatus', native_enum=False, length=20), nullable=False))
    op.add_column('quiz_progress', sa.Column('review_error', sa.Text(), nullable=True))
    op.add_column('quiz_requests', sa.Column('max_retry', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_requests', 'max_retry')
    op.drop_column('quiz_progress', 'review_error')
    op.drop_column('quiz_progress', 'review_status')
    op.drop_column('quiz_progress', 'started_at')
    op.drop_column('quiz_progress', 'attempt_count')
    # ### end Alembic commands ###
