"""fix name table module progress

Revision ID: 9c8d3a181ca6
Revises: 
Create Date: 2026-09-10 19:46:37.485383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8d3a181ca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kode IN ('E', 'F')", name='check_fase_kode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('cp_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("domain IN ('Bilangan', 'Aljabar dan Fungsi', 'Pengukuran', 'Geometri', 'Analisis Data dan Peluang', 'Fungsi', 'Kalkulus')", name='check_cp_domain'),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fase_id', 'domain', name='uq_cp_fase_domain')
    )
    op.create_index(op.f('ix_cp_fase_id'), 'cp', ['fase_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_city_id'), 'schools', ['city_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(length=255), nullable=True),
    sa.Column('nisn', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('classroom_type_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_type_id'], ['classroom_types.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_code'), 'classrooms', ['code'], unique=True)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISH', name='modulestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_classroom_id'), 'modules', ['classroom_id'], unique=False)
    op.create_index('ix_modules_published_classroom', 'modules', ['classroom_id'], unique=False, postgresql_where=sa.text("status = 'PUBLISH'"))
    op.create_table('student_classrooms',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'classroom_id')
    )
    op.create_index('idx_student_classrooms_student_classroom', 'student_classrooms', ['student_id', 'classroom_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('cp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cp_id'], ['cp.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapter_module', 'chapters', ['module_id', 'number'], unique=False)
    op.create_table('modules_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'module_id', name='uq_student_module_progress')
    )
    op.create_index(op.f('ix_modules_progress_module_id'), 'modules_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_modules_progress_student_id'), 'modules_progress', ['student_id'], unique=False)
    op.create_table('quiz_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('hots_count', sa.Integer(), nullable=False),
    sa.Column('lots_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='check_quiz_req_status'),
    sa.CheckConstraint('hots_count >= 0', name='check_quiz_req_hots'),
    sa.CheckConstraint('lots_count >= 0', name='check_quiz_req_lots'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_request_status', 'quiz_requests', ['status', 'id'], unique=False)
    op.create_index(op.f('ix_quiz_requests_module_id'), 'quiz_requests', ['module_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('readable_text', sa.Text(), nullable=False),
    sa.Column('review_priority', sa.Text(), server_default='normal', nullable=False),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('source_markup', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("block_type IN ('heading', 'text', 'formula', 'table', 'image')", name='check_block_type'),
    sa.CheckConstraint("review_priority IN ('low', 'normal', 'high')", name='check_block_review_priority'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_block_chapter_order', 'blocks', ['chapter_id', 'reading_order'], unique=False)
    op.create_table('chapters_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'chapter_id', name='uq_student_chapter_progress')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('out_dir', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('blocks_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='check_job_status'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_chapter', 'jobs', ['chapter_id', 'id'], unique=False)
    op.create_index('ix_job_status', 'jobs', ['status', 'id'], unique=False)
    op.create_table('quiz_request_chapters',
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_request_id', 'chapter_id')
    )
    op.create_table('soal_stimulus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('source_markup', sa.Text(), server_default='', nullable=False),
    sa.Column('readable_text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('source_reading_order_start', sa.Integer(), nullable=False),
    sa.Column('source_reading_order_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited')", name='check_stimulus_review'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soal_stimulus_chapter_id'), 'soal_stimulus', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_soal_stimulus_quiz_request_id'), 'soal_stimulus', ['quiz_request_id'], unique=False)
    op.create_table('soal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_request_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('stimulus_id', sa.Integer(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.CHAR(length=1), nullable=False),
    sa.Column('kesimpulan', sa.Text(), nullable=False),
    sa.Column('source_reading_order_start', sa.Integer(), nullable=False),
    sa.Column('source_reading_order_end', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('review_priority', sa.Text(), server_default='normal', nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("correct_option IN ('A', 'B', 'C', 'D')", name='check_soal_correct_opt'),
    sa.CheckConstraint("review_priority IN ('low', 'normal', 'high')", name='check_soal_priority'),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'rejected', 'edited')", name='check_soal_review'),
    sa.CheckConstraint('bloom_level BETWEEN 1 AND 6', name='check_soal_bloom'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_request_id'], ['quiz_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stimulus_id'], ['soal_stimulus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soal_chapter_id'), 'soal', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_soal_quiz_request_id'), 'soal', ['quiz_request_id'], unique=False)
    op.create_index(op.f('ix_soal_stimulus_id'), 'soal', ['stimulus_id'], unique=False)
    op.create_table('soal_langkah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soal_id', 'urutan', name='uq_soal_langkah_urutan')
    )
    op.create_index(op.f('ix_soal_langkah_soal_id'), 'soal_langkah', ['soal_id'], unique=False)
    op.create_table('soal_opsi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.CHAR(length=1), nullable=False),
    sa.Column('opsi_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("label IN ('A', 'B', 'C', 'D')", name='check_opsi_label'),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soal_id', 'label', name='uq_soal_opsi_label')
    )
    op.create_index(op.f('ix_soal_opsi_soal_id'), 'soal_opsi', ['soal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soal_opsi_soal_id'), table_name='soal_opsi')
    op.drop_table('soal_opsi')
    op.drop_index(op.f('ix_soal_langkah_soal_id'), table_name='soal_langkah')
    op.drop_table('soal_langkah')
    op.drop_index(op.f('ix_soal_stimulus_id'), table_name='soal')
    op.drop_index(op.f('ix_soal_quiz_request_id'), table_name='soal')
    op.drop_index(op.f('ix_soal_chapter_id'), table_name='soal')
    op.drop_table('soal')
    op.drop_index(op.f('ix_soal_stimulus_quiz_request_id'), table_name='soal_stimulus')
    op.drop_index(op.f('ix_soal_stimulus_chapter_id'), table_name='soal_stimulus')
    op.drop_table('soal_stimulus')
    op.drop_table('quiz_request_chapters')
    op.drop_index('ix_job_status', table_name='jobs')
    op.drop_index('ix_job_chapter', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('chapters_progress')
    op.drop_index('ix_block_chapter_order', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_quiz_requests_module_id'), table_name='quiz_requests')
    op.drop_index('ix_quiz_request_status', table_name='quiz_requests')
    op.drop_table('quiz_requests')
    op.drop_index(op.f('ix_modules_progress_student_id'), table_name='modules_progress')
    op.drop_index(op.f('ix_modules_progress_module_id'), table_name='modules_progress')
    op.drop_table('modules_progress')
    op.drop_index('ix_chapter_module', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('idx_student_classrooms_student_classroom', table_name='student_classrooms')
    op.drop_table('student_classrooms')
    op.drop_index('ix_modules_published_classroom', table_name='modules', postgresql_where=sa.text("status = 'PUBLISH'"))
    op.drop_index(op.f('ix_modules_classroom_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_schools_city_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_cp_fase_id'), table_name='cp')
    op.drop_table('cp')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fase')
    op.drop_table('classroom_types')
    op.drop_table('cities')
    # ### end Alembic commands ###
