"""update blocks

Revision ID: 9eaee4bf2398
Revises: 04e39ed293dd
Create Date: 2026-09-12 11:18:52.907213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eaee4bf2398'
down_revision: Union[str, Sequence[str], None] = '04e39ed293dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('previous_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_chapters_module_id'), 'chapters', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_module_id'), table_name='chapters')
    op.drop_column('blocks', 'previous_text')
    # ### end Alembic commands ###
