"""membuat tabel pertama

Revision ID: a3b3ed5a0e2e
Revises: 4df55953f70f
Create Date: 2026-09-21 15:58:28.128173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b3ed5a0e2e'
down_revision: Union[str, Sequence[str], None] = '4df55953f70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_quiz_progress_quiz_student'), 'quiz_progress', type_='unique')
    op.create_unique_constraint('uq_quiz_progress_student_attempt', 'quiz_progress', ['quiz_request_id', 'student_id', 'attempt_count'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quiz_progress_student_attempt', 'quiz_progress', type_='unique')
    op.create_unique_constraint(op.f('uq_quiz_progress_quiz_student'), 'quiz_progress', ['quiz_request_id', 'student_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
