"""quiz per bab counts

Revision ID: ae60159a3d24
Revises: 9eaee4bf2398
Create Date: 2026-09-12 14:56:52.626702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae60159a3d24'
down_revision: Union[str, Sequence[str], None] = '9eaee4bf2398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    hots_count/lots_count pindah dari quiz_requests (satu angka untuk seluruh request) ke
    quiz_request_chapters (per bab) -- guru menentukan alokasi soal sendiri tiap bab, bukan satu
    angka gabungan untuk semua bab dalam satu request. server_default='0' cuma buat aman kalau
    tabel ini sudah punya baris; drop_column di quiz_requests tidak butuh default (kolom dihapus).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_request_chapters', sa.Column('hots_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('quiz_request_chapters', sa.Column('lots_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('quiz_requests', 'hots_count')
    op.drop_column('quiz_requests', 'lots_count')
    # ### end Alembic commands ###
    op.create_check_constraint('check_quiz_req_chapter_hots', 'quiz_request_chapters', 'hots_count >= 0')
    op.create_check_constraint('check_quiz_req_chapter_lots', 'quiz_request_chapters', 'lots_count >= 0')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('check_quiz_req_chapter_lots', 'quiz_request_chapters', type_='check')
    op.drop_constraint('check_quiz_req_chapter_hots', 'quiz_request_chapters', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_requests', sa.Column('lots_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quiz_requests', sa.Column('hots_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('quiz_request_chapters', 'lots_count')
    op.drop_column('quiz_request_chapters', 'hots_count')
    # ### end Alembic commands ###
    op.create_check_constraint('check_quiz_req_hots', 'quiz_requests', 'hots_count >= 0')
    op.create_check_constraint('check_quiz_req_lots', 'quiz_requests', 'lots_count >= 0')
