"""add classroom

Revision ID: b2588adad314
Revises: 708fd34e3341
Create Date: 2026-09-08 01:20:08.544634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2588adad314'
down_revision: Union[str, Sequence[str], None] = '708fd34e3341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_schools_city_id'), 'schools', ['city_id'], unique=False)
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('teachers', 'deleted_at')
    op.drop_column('students', 'deleted_at')
    op.drop_index(op.f('ix_schools_city_id'), table_name='schools')
    op.drop_column('schools', 'deleted_at')
    op.drop_column('cities', 'deleted_at')
    # ### end Alembic commands ###
